#!/usr/bin/env bash
# ==============================================================================
# ProctorNet WireGuard Server Setup Script (P8 Task 9 / ADR-010)
#
# Idempotent provisioning script for WireGuard VPN server on Ubuntu / Debian.
# Configures:
#  - Linux kernel sysctl: ip_forward, fq queue discipline, BBR congestion control
#  - WireGuard interface (wg0) with MTU 1380 (prevents fragmentation)
#  - nftables strict default-drop firewall policy:
#    * Only peers (10.8.0.0/16) -> App port 443 & LiveKit SFU ports (7880-7882)
#    * Cross-peer forwarding blocked
#    * External LAN / metadata forwarding blocked
#
# No hardcoded IPs or keys. Set via environment or Terraform.
# ==============================================================================

set -euo pipefail

# ── Configuration Variables (Env overrides) ───────────────────────────────────
WG_INTERFACE="${WG_INTERFACE:-wg0}"
WG_PORT="${WG_PORT:-51820}"
WG_SUBNET="${WG_SUBNET:-10.8.0.0/16}"
WG_GATEWAY_IP="${WG_GATEWAY_IP:-10.8.0.1/16}"
WG_MTU="${WG_MTU:-1380}"
APP_PORT="${APP_PORT:-443}"
SFU_HTTP_PORT="${SFU_HTTP_PORT:-7880}"
SFU_TCP_PORT="${SFU_TCP_PORT:-7881}"
SFU_UDP_PORT="${SFU_UDP_PORT:-7882}"
WG_CONFIG_DIR="/etc/wireguard"
WG_CONF_FILE="${WG_CONFIG_DIR}/${WG_INTERFACE}.conf"

echo "=== [1/6] ProctorNet WireGuard Setup Starting ==="
echo "Interface:       ${WG_INTERFACE}"
echo "Subnet:          ${WG_SUBNET} (Gateway: ${WG_GATEWAY_IP})"
echo "Listen Port:     ${WG_PORT}"
echo "MTU:             ${WG_MTU}"
echo "App Port:        ${APP_PORT}"
echo "SFU Ports:       ${SFU_HTTP_PORT}, ${SFU_TCP_PORT}, ${SFU_UDP_PORT}"

# Ensure root
if [ "$(id -u)" -ne 0 ]; then
  echo "[-] ERROR: This script must be run as root." >&2
  exit 1
fi

# ── 1. Install Dependencies ───────────────────────────────────────────────────
echo "=== [2/6] Installing WireGuard and nftables ==="
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq wireguard wireguard-tools nftables curl jq

# ── 2. Kernel Tuning (Sysctl) ─────────────────────────────────────────────────
echo "=== [3/6] Applying Kernel Sysctl Tuning (BBR, FQ, IP Forwarding) ==="
cat > /etc/sysctl.d/99-wireguard-proctornet.conf << 'EOF'
# ProctorNet VPN Kernel Optimizations
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 0
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
EOF

sysctl --system > /dev/null
echo "[+] Kernel parameters applied successfully."

# ── 3. WireGuard Server Keypair Generation (Idempotent) ───────────────────────
echo "=== [4/6] Ensuring Server Cryptographic Keys ==="
mkdir -p "${WG_CONFIG_DIR}"
chmod 700 "${WG_CONFIG_DIR}"

if [ -n "${WG_SERVER_PRIVATE_KEY:-}" ]; then
  SERVER_PRIVATE_KEY="${WG_SERVER_PRIVATE_KEY}"
  SERVER_PUBLIC_KEY=$(echo "${SERVER_PRIVATE_KEY}" | wg pubkey)
elif [ -f "${WG_CONFIG_DIR}/server_private.key" ]; then
  SERVER_PRIVATE_KEY=$(cat "${WG_CONFIG_DIR}/server_private.key")
  SERVER_PUBLIC_KEY=$(cat "${WG_CONFIG_DIR}/server_public.key")
  echo "[+] Reusing existing server keypair."
else
  SERVER_PRIVATE_KEY=$(wg genkey)
  SERVER_PUBLIC_KEY=$(echo "${SERVER_PRIVATE_KEY}" | wg pubkey)
  echo "${SERVER_PRIVATE_KEY}" > "${WG_CONFIG_DIR}/server_private.key"
  echo "${SERVER_PUBLIC_KEY}" > "${WG_CONFIG_DIR}/server_public.key"
  chmod 600 "${WG_CONFIG_DIR}/server_private.key"
  chmod 644 "${WG_CONFIG_DIR}/server_public.key"
  echo "[+] Generated new WireGuard server keypair."
fi

# ── 4. WireGuard Interface Configuration ──────────────────────────────────────
echo "=== [5/6] Generating ${WG_CONF_FILE} ==="
cat > "${WG_CONF_FILE}" << EOF
# Auto-generated by ProctorNet setup-wireguard.sh
[Interface]
Address = ${WG_GATEWAY_IP}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIVATE_KEY}
MTU = ${WG_MTU}
SaveConfig = false

# Peers are dynamically provisioned via vpn-agent / outbox worker
EOF

chmod 600 "${WG_CONF_FILE}"

# ── 5. nftables Policy: Default Drop, Allow App & SFU Only ────────────────────
echo "=== [6/6] Configuring nftables Security Boundary ==="
cat > /etc/nftables.conf << EOF
#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # Accept loopback
        iif lo accept

        # Accept established/related connections
        ct state established,related accept

        # Accept ICMP (ping) for diagnostics
        ip protocol icmp accept

        # Accept SSH management
        tcp dport 22 accept

        # Accept WireGuard UDP traffic from anywhere
        udp dport ${WG_PORT} accept

        # Accept App 443 and SFU ports from WireGuard subnet (${WG_SUBNET})
        iifname "${WG_INTERFACE}" ip saddr ${WG_SUBNET} tcp dport { ${APP_PORT}, ${SFU_HTTP_PORT}, ${SFU_TCP_PORT} } accept
        iifname "${WG_INTERFACE}" ip saddr ${WG_SUBNET} udp dport ${SFU_UDP_PORT} accept

        # Drop everything else
        counter drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;

        # Allow established/related return traffic
        ct state established,related accept

        # Drop peer-to-peer and peer-to-external internet forwarding (isolated tunnel)
        counter drop
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
EOF

nft -f /etc/nftables.conf
systemctl enable nftables > /dev/null 2>&1 || true
systemctl restart nftables > /dev/null 2>&1 || true

# ── 6. Restart WireGuard Interface ────────────────────────────────────────────
systemctl enable "wg-quick@${WG_INTERFACE}" > /dev/null 2>&1 || true
systemctl restart "wg-quick@${WG_INTERFACE}"

echo ""
echo "=========================================================================="
echo " WireGuard Setup Complete!"
echo " Server Public Key:  ${SERVER_PUBLIC_KEY}"
echo " Server Endpoint:    $(curl -s https://api.ipify.org 2>/dev/null || echo '<SERVER_PUBLIC_IP>'):${WG_PORT}"
echo " Subnet:             ${WG_SUBNET}"
echo " MTU:                ${WG_MTU}"
echo "=========================================================================="
echo "To enable in ProctorNet deployment, configure in backend environment:"
echo "  VPN_ENABLED=true"
echo "  VPN_SERVER_PUBLIC_KEY=${SERVER_PUBLIC_KEY}"
echo "  VPN_SERVER_IP=$(curl -s https://api.ipify.org 2>/dev/null || echo '<SERVER_PUBLIC_IP>')"
echo "  VPN_SERVER_PORT=${WG_PORT}"
echo "=========================================================================="
