import http from 'k6/http'
import { check, sleep } from 'k6'
import { Trend, Rate, Counter } from 'k6/metrics'

// Custom Trend Metrics
const loginDuration = new Trend('proctornet_login_duration_ms')
const examListDuration = new Trend('proctornet_exam_list_duration_ms')
const startExamDuration = new Trend('proctornet_start_exam_duration_ms')
const autosaveDuration = new Trend('proctornet_autosave_duration_ms')
const submitDuration = new Trend('proctornet_submit_duration_ms')
const errorRate = new Rate('proctornet_error_rate')
const successfulSubmissions = new Counter('proctornet_successful_submissions')

// Load fixture data generated by seed_loadtest_fixture.js
let studentsData = []
try {
  studentsData = JSON.parse(open('../../../reports/load/baseline/students.json'))
} catch (_e) {
  // Fallback default test user if file not yet written
  studentsData = [{ email: 'loadtest-student-1@proctornet.test', password: 'Student123!' }]
}

const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1:5000'
const VUS = parseInt(__ENV.VUS || '50', 10)
const TEST_DURATION = __ENV.DURATION || '30s'

export const options = {
  scenarios: {
    exam_cohort_simulation: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '10s', target: VUS },          // Ramp up cohort
        { duration: TEST_DURATION, target: VUS },   // Concurrent exam answering burst
        { duration: '5s', target: 0 },              // Cool down
      ],
      gracefulRampDown: '5s',
    },
  },
  thresholds: {
    // SLOs (§10.2):
    // Autosave p95 < 500ms
    // Error rate < 1%
    proctornet_error_rate: ['rate<0.01'],
    proctornet_autosave_duration_ms: ['p(95)<500'],
    proctornet_start_exam_duration_ms: ['p(95)<1500'],
    http_req_failed: ['rate<0.01'],
  },
}

export default function () {
  // Select student based on VU id
  const index = (__VU - 1) % studentsData.length
  const user = studentsData[index]
  const jar = http.cookieJar()

  // ── 1. Student Login (uses USN and password) ──
  const loginPayload = JSON.stringify({
    usn: user.usn,
    password: user.password,
  })

  const loginRes = http.post(`${BASE_URL}/api/auth/student/login`, loginPayload, {
    headers: { 'Content-Type': 'application/json' },
    jar,
  })

  loginDuration.add(loginRes.timings.duration)
  const loginOk = check(loginRes, {
    'login status is 200': (r) => r.status === 200,
  })

  if (!loginOk) {
    errorRate.add(1)
    return
  }
  errorRate.add(0)

  let token = ''
  try {
    const data = loginRes.json()
    token = data.token || ''
  } catch (_e) {}

  const authHeaders = {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }

  sleep(0.5)

  // ── 2. Discover Available Exams ──
  const listRes = http.get(`${BASE_URL}/api/student/exams`, { headers: authHeaders, jar })
  examListDuration.add(listRes.timings.duration)
  check(listRes, { 'list exams status is 200': (r) => r.status === 200 })

  let examId = user.examId
  if (!examId) {
    try {
      const exams = listRes.json()
      if (Array.isArray(exams) && exams.length > 0) {
        examId = exams[0].id
      }
    } catch (_err) {}
  }

  if (!examId) {
    errorRate.add(1)
    return
  }

  sleep(0.5)

  // ── 3. Start or Resume Exam (Burst Start) ──
  const startRes = http.post(`${BASE_URL}/api/student/exams/${examId}/start`, '{}', {
    headers: authHeaders,
    jar,
  })
  startExamDuration.add(startRes.timings.duration)

  const startOk = check(startRes, {
    'start exam status is 200': (r) => r.status === 200,
  })

  if (!startOk) {
    errorRate.add(1)
    return
  }
  errorRate.add(0)

  // Parse questions from start response
  let questionIds = []
  try {
    const data = startRes.json()
    if (data.questions && Array.isArray(data.questions)) {
      questionIds = data.questions.map((q) => q.id)
    } else if (data.exam && data.exam.questions && Array.isArray(data.exam.questions)) {
      questionIds = data.exam.questions.map((q) => q.id)
    }
  } catch (_e) {}

  // ── 4. Periodic Autosave Loop (autosave every 5s) ──
  const questionsToAnswer = questionIds.slice(0, 3)
  for (let i = 0; i < questionsToAnswer.length; i++) {
    const qid = questionsToAnswer[i]
    sleep(1.0) // Thinking delay

    const autosavePayload = JSON.stringify({
      questionId: qid,
      answer: 'Deterministic loadtest option B',
      answers: { [qid]: 'Deterministic loadtest option B' },
    })

    const ansRes = http.post(`${BASE_URL}/api/student/exams/${examId}/autosave`, autosavePayload, {
      headers: authHeaders,
      jar,
    })

    autosaveDuration.add(ansRes.timings.duration)
    const ansOk = check(ansRes, {
      'autosave status is 200': (r) => r.status === 200,
    })

    if (!ansOk) {
      errorRate.add(1)
    } else {
      errorRate.add(0)
    }
  }

  sleep(1.0)

  // ── 5. Submit Examination ──
  const submitPayload = JSON.stringify({
    answers: questionsToAnswer.reduce((acc, qid) => {
      acc[qid] = 'Deterministic loadtest option B'
      return acc
    }, {}),
  })

  const submitRes = http.post(`${BASE_URL}/api/student/exams/${examId}/submit`, submitPayload, {
    headers: authHeaders,
    jar,
  })

  submitDuration.add(submitRes.timings.duration)
  const submitOk = check(submitRes, {
    'submit status is 200': (r) => r.status === 200,
  })

  if (submitOk) {
    successfulSubmissions.add(1)
    errorRate.add(0)
  } else {
    errorRate.add(1)
  }

  sleep(0.5)
}
