
-- =============================================================
-- Extensions
-- =============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- =============================================================
-- Base Schema DDL (Generated by Prisma Migrate Diff)
-- =============================================================
-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'FACULTY', 'STUDENT');

-- CreateEnum
CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "ProfileStatus" AS ENUM ('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'LOCKED');

-- CreateEnum
CREATE TYPE "ExamStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'SCHEDULED', 'LIVE', 'ENDED', 'EVALUATED', 'RESULT_PUBLISHED');

-- CreateEnum
CREATE TYPE "Difficulty" AS ENUM ('EASY', 'MEDIUM', 'HARD');

-- CreateEnum
CREATE TYPE "AttemptStatus" AS ENUM ('READY', 'ACTIVE', 'SUBMITTED', 'SUSPENDED', 'TERMINATED', 'TIMED_OUT');

-- CreateEnum
CREATE TYPE "ResultStatus" AS ENUM ('CLEAN', 'FLAGGED', 'SUSPECTED', 'DISQUALIFIED');

-- CreateEnum
CREATE TYPE "ViolationType" AS ENUM ('TAB_SWITCH', 'FULLSCREEN_EXIT', 'MULTIPLE_FACES', 'NO_FACE', 'FACE_MISMATCH', 'AUDIO_DETECTED', 'VOICE_DETECTED', 'SUSPICIOUS_OBJECT', 'DEVTOOLS_OPENED', 'KEYBOARD_SHORTCUT', 'WINDOW_BLUR', 'IP_CHANGE', 'VM_DETECTED');

-- CreateEnum
CREATE TYPE "Severity" AS ENUM ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "EvidenceStatus" AS ENUM ('NONE', 'PENDING', 'UPLOADED', 'FAILED');

-- CreateEnum
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'PUBLISHED', 'FAILED');

-- CreateTable
CREATE TABLE "departments" (
    "code" VARCHAR(16) NOT NULL,
    "name" VARCHAR(128) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "departments_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "admins" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admins_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_settings" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updated_by" UUID,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "platform_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "faculties" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "department_code" VARCHAR(16) NOT NULL,
    "employee_id" TEXT NOT NULL,
    "phone" TEXT,
    "id_card_photo_key" TEXT,
    "profile_photo_key" TEXT,
    "must_change_password" BOOLEAN NOT NULL DEFAULT false,
    "is_approved" BOOLEAN NOT NULL DEFAULT true,
    "approved_by" UUID,
    "approved_at" TIMESTAMP(3),
    "is_suspended" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "faculties_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "students" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "usn" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "department_code" VARCHAR(16) NOT NULL,
    "semester" SMALLINT NOT NULL DEFAULT 1,
    "phone" TEXT,
    "face_photo_key" TEXT,
    "id_card_photo_key" TEXT,
    "face_match_score" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "must_change_password" BOOLEAN NOT NULL DEFAULT false,
    "approval_status" "ApprovalStatus" NOT NULL DEFAULT 'APPROVED',
    "approved_by" UUID,
    "approved_at" TIMESTAMP(3),
    "is_suspended" BOOLEAN NOT NULL DEFAULT false,
    "profile_status" "ProfileStatus" NOT NULL DEFAULT 'PENDING',
    "face_subject_id" TEXT,
    "face_embedding_ref" TEXT,
    "id_document_key" TEXT,
    "id_cropped_face_key" TEXT,
    "id_ocr_fields" JSONB,
    "consent_timestamp" TIMESTAMP(3),
    "biometric_enroll_deadline" TIMESTAMP(3),
    "rejection_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "exams" (
    "id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "description" TEXT,
    "faculty_id" UUID NOT NULL,
    "start_time" TIMESTAMP(3) NOT NULL,
    "end_time" TIMESTAMP(3) NOT NULL,
    "duration" INTEGER NOT NULL DEFAULT 60,
    "total_marks" DOUBLE PRECISION NOT NULL DEFAULT 100,
    "negative_marking" BOOLEAN NOT NULL DEFAULT false,
    "negative_value" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "questions_per_student" INTEGER NOT NULL DEFAULT 0,
    "randomise_questions" BOOLEAN NOT NULL DEFAULT true,
    "randomise_options" BOOLEAN NOT NULL DEFAULT true,
    "allowed_departments" TEXT[],
    "allowed_semesters" SMALLINT[],
    "inv_id" TEXT NOT NULL,
    "inv_password_hash" TEXT NOT NULL,
    "status" "ExamStatus" NOT NULL DEFAULT 'DRAFT',
    "camera_required" BOOLEAN NOT NULL DEFAULT true,
    "mic_required" BOOLEAN NOT NULL DEFAULT false,
    "browser_lock" BOOLEAN NOT NULL DEFAULT true,
    "full_screen_mode" BOOLEAN NOT NULL DEFAULT true,
    "watermark_required" BOOLEAN NOT NULL DEFAULT true,
    "tab_switch_limit" INTEGER NOT NULL DEFAULT 3,
    "ai_reverify_interval" INTEGER NOT NULL DEFAULT 10,
    "mobile_detect_config" JSONB,
    "is_paused" BOOLEAN NOT NULL DEFAULT false,
    "paused_by" UUID,
    "pause_reason" TEXT,
    "results_released" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "questions" (
    "id" UUID NOT NULL,
    "exam_id" UUID NOT NULL,
    "question_text" TEXT NOT NULL,
    "image_key" TEXT,
    "marks" DOUBLE PRECISION NOT NULL,
    "negative_marks" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "difficulty" "Difficulty" NOT NULL DEFAULT 'MEDIUM',
    "order" INTEGER NOT NULL DEFAULT 0,
    "tags" TEXT[],
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "question_options" (
    "id" UUID NOT NULL,
    "question_id" UUID NOT NULL,
    "text" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL DEFAULT false,
    "order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "question_options_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "exam_attempts" (
    "id" UUID NOT NULL,
    "exam_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "status" "AttemptStatus" NOT NULL DEFAULT 'READY',
    "started_at" TIMESTAMP(3),
    "expires_at" TIMESTAMP(3),
    "submitted_at" TIMESTAMP(3),
    "suspended_at" TIMESTAMP(3),
    "total_suspended_ms" INTEGER NOT NULL DEFAULT 0,
    "watermark_seed" TEXT NOT NULL,
    "shuffle_seed" TEXT,
    "flag_count" INTEGER NOT NULL DEFAULT 0,
    "termination_reason" TEXT,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "vpn_ip" TEXT,
    "vpn_key_expiry" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exam_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attempt_questions" (
    "id" UUID NOT NULL,
    "attempt_id" UUID NOT NULL,
    "question_id" UUID NOT NULL,
    "display_order" INTEGER NOT NULL,
    "option_order" SMALLINT[],

    CONSTRAINT "attempt_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "answers" (
    "id" UUID NOT NULL,
    "attempt_id" UUID NOT NULL,
    "attempt_question_id" UUID NOT NULL,
    "selected_option_id" UUID,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "saved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "time_taken_secs" INTEGER NOT NULL DEFAULT 0,
    "auto_score" DOUBLE PRECISION,

    CONSTRAINT "answers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "exam_results" (
    "id" UUID NOT NULL,
    "attempt_id" UUID NOT NULL,
    "exam_id" UUID NOT NULL,
    "score" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "total_marks" DOUBLE PRECISION NOT NULL,
    "correct_count" INTEGER NOT NULL DEFAULT 0,
    "wrong_count" INTEGER NOT NULL DEFAULT 0,
    "unanswered_count" INTEGER NOT NULL DEFAULT 0,
    "percentage" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rank" INTEGER,
    "time_taken" INTEGER NOT NULL DEFAULT 0,
    "flag_count" INTEGER NOT NULL DEFAULT 0,
    "status" "ResultStatus" NOT NULL DEFAULT 'CLEAN',
    "is_released" BOOLEAN NOT NULL DEFAULT false,
    "released_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exam_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "violation_events" (
    "id" BIGSERIAL NOT NULL,
    "attempt_id" UUID NOT NULL,
    "event_type" "ViolationType" NOT NULL,
    "severity" "Severity" NOT NULL,
    "server_timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "client_timestamp" TIMESTAMP(3),
    "source" TEXT NOT NULL DEFAULT 'CLIENT_EVENT',
    "metadata" JSONB,
    "evidence_key" TEXT,
    "evidence_status" "EvidenceStatus" NOT NULL DEFAULT 'NONE',
    "inv_action" TEXT,
    "inv_action_note" TEXT,

    CONSTRAINT "violation_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" BIGSERIAL NOT NULL,
    "actor_id" UUID,
    "actor_role" TEXT NOT NULL,
    "faculty_id" UUID,
    "student_id" UUID,
    "action" TEXT NOT NULL,
    "resource_type" TEXT,
    "resource_id" TEXT,
    "attempt_id" UUID,
    "request_id" TEXT,
    "metadata" JSONB,
    "ip_address" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_messages" (
    "id" BIGSERIAL NOT NULL,
    "exam_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "sender_role" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_read" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox_events" (
    "id" BIGSERIAL NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "OutboxStatus" NOT NULL DEFAULT 'PENDING',
    "next_attempt_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMP(3),

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "key" TEXT NOT NULL,
    "request_hash" TEXT NOT NULL,
    "response_status" INTEGER NOT NULL,
    "response_body" JSONB NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "processed_events" (
    "id" UUID NOT NULL,
    "event_id" TEXT NOT NULL,
    "handler_name" TEXT NOT NULL,
    "processed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "processed_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vpn_ip_pool" (
    "id" UUID NOT NULL,
    "ip_address" TEXT NOT NULL,
    "is_allocated" BOOLEAN NOT NULL DEFAULT false,
    "allocated_to" UUID,
    "allocated_at" TIMESTAMP(3),

    CONSTRAINT "vpn_ip_pool_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vpn_peers" (
    "id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "ip_address" TEXT NOT NULL,
    "public_key" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vpn_peers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity_verifications" (
    "id" UUID NOT NULL,
    "attempt_id" UUID NOT NULL,
    "live_face_match_score" DOUBLE PRECISION NOT NULL,
    "id_card_ocr_usn" TEXT,
    "id_card_match_result" BOOLEAN NOT NULL,
    "face_with_id_key" TEXT NOT NULL,
    "verified_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL,

    CONSTRAINT "identity_verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_audit_logs" (
    "id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "attempt_id" UUID,
    "check_type" TEXT NOT NULL,
    "score" DOUBLE PRECISION,
    "status" TEXT NOT NULL,
    "details" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reverification_logs" (
    "id" UUID NOT NULL,
    "attempt_id" UUID NOT NULL,
    "check_time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "face_match_score" DOUBLE PRECISION NOT NULL,
    "result" TEXT NOT NULL,
    "camera_frame_key" TEXT,

    CONSTRAINT "reverification_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "device_check_logs" (
    "id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "attempt_id" UUID,
    "agent_connected" BOOLEAN NOT NULL DEFAULT true,
    "blocked_processes" TEXT[],
    "virtual_cams" TEXT[],
    "is_subnet_matched" BOOLEAN NOT NULL DEFAULT true,
    "client_ip" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PASSED',
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "device_check_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invigilator_sessions" (
    "id" UUID NOT NULL,
    "exam_id" UUID NOT NULL,
    "inv_id" TEXT NOT NULL,
    "id_card_photo_key" TEXT NOT NULL,
    "id_card_ocr_result" TEXT,
    "login_time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "session_expiry" TIMESTAMP(3) NOT NULL,
    "ip_address" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "invigilator_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "collusion_reports" (
    "id" UUID NOT NULL,
    "exam_id" UUID NOT NULL,
    "student1_id" UUID NOT NULL,
    "student2_id" UUID NOT NULL,
    "similarity_score" DOUBLE PRECISION NOT NULL,
    "common_questions" TEXT[],
    "matching_wrong_answers" TEXT[],
    "is_flagged" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "collusion_reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "announcements" (
    "id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "posted_by" UUID NOT NULL,
    "target" TEXT NOT NULL,
    "target_department" TEXT,
    "priority" TEXT NOT NULL DEFAULT 'NORMAL',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "read_by" TEXT[],

    CONSTRAINT "announcements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "biometric_override_logs" (
    "id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "approver_id" UUID NOT NULL,
    "reason" TEXT NOT NULL,
    "prev_status" TEXT NOT NULL,
    "new_status" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "biometric_override_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "admins_email_key" ON "admins"("email");

-- CreateIndex
CREATE UNIQUE INDEX "platform_settings_key_key" ON "platform_settings"("key");

-- CreateIndex
CREATE UNIQUE INDEX "faculties_email_key" ON "faculties"("email");

-- CreateIndex
CREATE UNIQUE INDEX "faculties_employee_id_key" ON "faculties"("employee_id");

-- CreateIndex
CREATE UNIQUE INDEX "students_usn_key" ON "students"("usn");

-- CreateIndex
CREATE UNIQUE INDEX "students_email_key" ON "students"("email");

-- CreateIndex
CREATE UNIQUE INDEX "exams_inv_id_key" ON "exams"("inv_id");

-- CreateIndex
CREATE INDEX "question_options_question_id_idx" ON "question_options"("question_id");

-- CreateIndex
CREATE UNIQUE INDEX "exam_attempts_exam_id_student_id_key" ON "exam_attempts"("exam_id", "student_id");

-- CreateIndex
CREATE UNIQUE INDEX "attempt_questions_attempt_id_display_order_key" ON "attempt_questions"("attempt_id", "display_order");

-- CreateIndex
CREATE UNIQUE INDEX "attempt_questions_attempt_id_question_id_key" ON "attempt_questions"("attempt_id", "question_id");

-- CreateIndex
CREATE UNIQUE INDEX "answers_attempt_question_id_key" ON "answers"("attempt_question_id");

-- CreateIndex
CREATE UNIQUE INDEX "exam_results_attempt_id_key" ON "exam_results"("attempt_id");

-- CreateIndex
CREATE UNIQUE INDEX "processed_events_event_id_handler_name_key" ON "processed_events"("event_id", "handler_name");

-- CreateIndex
CREATE UNIQUE INDEX "vpn_ip_pool_ip_address_key" ON "vpn_ip_pool"("ip_address");

-- CreateIndex
CREATE UNIQUE INDEX "vpn_peers_ip_address_key" ON "vpn_peers"("ip_address");

-- CreateIndex
CREATE UNIQUE INDEX "vpn_peers_public_key_key" ON "vpn_peers"("public_key");

-- CreateIndex
CREATE UNIQUE INDEX "identity_verifications_attempt_id_key" ON "identity_verifications"("attempt_id");

-- AddForeignKey
ALTER TABLE "faculties" ADD CONSTRAINT "faculties_department_code_fkey" FOREIGN KEY ("department_code") REFERENCES "departments"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_department_code_fkey" FOREIGN KEY ("department_code") REFERENCES "departments"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exams" ADD CONSTRAINT "exams_faculty_id_fkey" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "question_options" ADD CONSTRAINT "question_options_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exam_attempts" ADD CONSTRAINT "exam_attempts_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exam_attempts" ADD CONSTRAINT "exam_attempts_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attempt_questions" ADD CONSTRAINT "attempt_questions_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attempt_questions" ADD CONSTRAINT "attempt_questions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "answers" ADD CONSTRAINT "answers_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "answers" ADD CONSTRAINT "answers_attempt_question_id_fkey" FOREIGN KEY ("attempt_question_id") REFERENCES "attempt_questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "answers" ADD CONSTRAINT "answers_selected_option_id_fkey" FOREIGN KEY ("selected_option_id") REFERENCES "question_options"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "violation_events" ADD CONSTRAINT "violation_events_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_faculty_id_fkey" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity_verifications" ADD CONSTRAINT "identity_verifications_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_audit_logs" ADD CONSTRAINT "verification_audit_logs_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reverification_logs" ADD CONSTRAINT "reverification_logs_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "device_check_logs" ADD CONSTRAINT "device_check_logs_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "exam_attempts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invigilator_sessions" ADD CONSTRAINT "invigilator_sessions_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "collusion_reports" ADD CONSTRAINT "collusion_reports_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;



-- =============================================================
-- P3 Custom Indexes (Partial, GIN, Composite)
-- =============================================================

-- Partial unique index: Single correct option per question
CREATE UNIQUE INDEX IF NOT EXISTS "idx_question_single_correct" ON "question_options" ("question_id") WHERE "is_correct" = true;

-- Partial index: Active attempt expiry sweeper
CREATE INDEX IF NOT EXISTS "idx_exam_attempts_active_expiry" ON "exam_attempts" ("status", "expires_at") WHERE "status" = 'ACTIVE';

-- Partial index: Pending violation evidence upload sweeper
CREATE INDEX IF NOT EXISTS "idx_violation_events_pending" ON "violation_events" ("evidence_status") WHERE "evidence_status" = 'PENDING';

-- Partial index: Pending outbox events queue
CREATE INDEX IF NOT EXISTS "idx_outbox_events_pending" ON "outbox_events" ("next_attempt_at", "id") WHERE "status" = 'PENDING';

-- Query-driven composite indexes
CREATE INDEX IF NOT EXISTS "idx_exam_attempts_exam_status" ON "exam_attempts" ("exam_id", "status");
CREATE INDEX IF NOT EXISTS "idx_exam_attempts_student_status" ON "exam_attempts" ("student_id", "status");
CREATE INDEX IF NOT EXISTS "idx_attempt_questions_attempt_display" ON "attempt_questions" ("attempt_id", "display_order");
CREATE INDEX IF NOT EXISTS "idx_violation_events_attempt_time" ON "violation_events" ("attempt_id", "server_timestamp" DESC);
CREATE INDEX IF NOT EXISTS "idx_violation_events_severity_time" ON "violation_events" ("severity", "server_timestamp" DESC);
CREATE INDEX IF NOT EXISTS "idx_exam_results_exam_id" ON "exam_results" ("exam_id");
CREATE INDEX IF NOT EXISTS "idx_questions_exam_id" ON "questions" ("exam_id");
CREATE INDEX IF NOT EXISTS "idx_chat_messages_exam_student_id" ON "chat_messages" ("exam_id", "student_id", "id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_actor_id" ON "audit_logs" ("actor_id", "id" DESC);
CREATE INDEX IF NOT EXISTS "idx_audit_logs_resource" ON "audit_logs" ("resource_type", "resource_id", "id" DESC);

-- GIN indexes for array containment and trigram search
CREATE INDEX IF NOT EXISTS "idx_exams_allowed_departments_gin" ON "exams" USING GIN ("allowed_departments");
CREATE INDEX IF NOT EXISTS "idx_exams_allowed_semesters_gin" ON "exams" USING GIN ("allowed_semesters");
CREATE INDEX IF NOT EXISTS "idx_students_name_trgm_gin" ON "students" USING GIN ("name" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "idx_students_usn_trgm_gin" ON "students" USING GIN ("usn" gin_trgm_ops);

-- =============================================================
-- Domain CHECK Constraints
-- =============================================================
ALTER TABLE "questions" ADD CONSTRAINT "chk_questions_marks_positive" CHECK ("marks" > 0);
ALTER TABLE "questions" ADD CONSTRAINT "chk_questions_negative_marks_bound" CHECK ("negative_marks" >= 0 AND "negative_marks" <= "marks");
ALTER TABLE "questions" ADD CONSTRAINT "chk_questions_text_length" CHECK (char_length("question_text") > 0 AND char_length("question_text") <= 5000);

ALTER TABLE "question_options" ADD CONSTRAINT "chk_question_options_text_length" CHECK (char_length("text") > 0 AND char_length("text") <= 500);

ALTER TABLE "exam_attempts" ADD CONSTRAINT "chk_attempt_expiry_after_start" CHECK ("expires_at" IS NULL OR "started_at" IS NULL OR "expires_at" >= "started_at");

-- =============================================================
-- Table Storage Parameters & Aggressive Autovacuum (HOT Updates)
-- =============================================================
ALTER TABLE "answers" SET (fillfactor = 80, autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.02);
ALTER TABLE "exam_attempts" SET (fillfactor = 80, autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.02);
