/**
 * Proctoring Violation Types, Canonical Severities & Cooldowns
 */

const CANONICAL_SEVERITY = {
  TAB_SWITCH: 'MEDIUM',
  FULLSCREEN_EXIT: 'HIGH',
  MULTIPLE_FACES: 'HIGH',
  NO_FACE: 'MEDIUM',
  FACE_MISMATCH: 'CRITICAL',
  AUDIO_DETECTED: 'MEDIUM',
  VOICE_DETECTED: 'HIGH',
  SUSPICIOUS_OBJECT: 'HIGH',
  DEVTOOLS_OPENED: 'CRITICAL',
  KEYBOARD_SHORTCUT: 'MEDIUM',
  WINDOW_BLUR: 'LOW',
  IP_CHANGE: 'CRITICAL',
  VM_DETECTED: 'CRITICAL'
}

const FLAG_COOLDOWNS = {
  TAB_SWITCH: 2000,
  FULLSCREEN_EXIT: 2000,
  MULTIPLE_FACES: 3000,
  NO_FACE: 3000,
  FACE_MISMATCH: 5000,
  AUDIO_DETECTED: 3000,
  VOICE_DETECTED: 3000,
  SUSPICIOUS_OBJECT: 5000,
  DEVTOOLS_OPENED: 5000,
  KEYBOARD_SHORTCUT: 1000,
  WINDOW_BLUR: 2000,
  IP_CHANGE: 10000,
  VM_DETECTED: 10000,
  DEFAULT: 3000
}

module.exports = {
  CANONICAL_SEVERITY,
  FLAG_COOLDOWNS
}
