/**
 * AUTO-GENERATED from shared/violationTypes.json - DO NOT EDIT MANUALLY.
 * Run "node scripts/generate-violation-types.js" to regenerate.
 */

export const VIOLATION_TYPES = Object.freeze({
  "TAB_SWITCH": "TAB_SWITCH",
  "FULLSCREEN_EXIT": "FULLSCREEN_EXIT",
  "MULTIPLE_FACES": "MULTIPLE_FACES",
  "NO_FACE": "NO_FACE",
  "FACE_MISMATCH": "FACE_MISMATCH",
  "AUDIO_DETECTED": "AUDIO_DETECTED",
  "VOICE_DETECTED": "VOICE_DETECTED",
  "SUSPICIOUS_OBJECT": "SUSPICIOUS_OBJECT",
  "DEVTOOLS_OPENED": "DEVTOOLS_OPENED",
  "KEYBOARD_SHORTCUT": "KEYBOARD_SHORTCUT",
  "WINDOW_BLUR": "WINDOW_BLUR",
  "IP_CHANGE": "IP_CHANGE",
  "VM_DETECTED": "VM_DETECTED",
  "SCREEN_SHARE_STOPPED": "SCREEN_SHARE_STOPPED",
  "VPN_DISCONNECT": "VPN_DISCONNECT",
  "VPN_IP_MISMATCH": "VPN_IP_MISMATCH",
  "UNAUTHORIZED_APPLICATION": "UNAUTHORIZED_APPLICATION",
  "VIRTUAL_CAMERA_DETECTED": "VIRTUAL_CAMERA_DETECTED",
  "REMOTE_SESSION_DETECTED": "REMOTE_SESSION_DETECTED",
  "VIRTUAL_MACHINE_DETECTED": "VIRTUAL_MACHINE_DETECTED",
  "MULTIPLE_DISPLAYS": "MULTIPLE_DISPLAYS",
  "AGENT_DISCONNECTED": "AGENT_DISCONNECTED",
  "AGENT_TAMPERED": "AGENT_TAMPERED",
  "AGENT_POLICY_INVALID": "AGENT_POLICY_INVALID"
})

export const CLIENT_VIOLATION_MAP = Object.freeze({
  "TAB_SWITCH": "TAB_SWITCH",
  "FULLSCREEN_EXIT": "FULLSCREEN_EXIT",
  "MULTIPLE_FACES": "MULTIPLE_FACES",
  "MULTIPLE_FACES_DETECTED": "MULTIPLE_FACES",
  "NO_FACE": "NO_FACE",
  "NO_FACE_DETECTED": "NO_FACE",
  "FACE_MISMATCH": "FACE_MISMATCH",
  "FACE_NOT_MATCHED": "FACE_MISMATCH",
  "AUDIO_DETECTED": "AUDIO_DETECTED",
  "VOICE_DETECTED": "VOICE_DETECTED",
  "SUSPICIOUS_OBJECT": "SUSPICIOUS_OBJECT",
  "DEVTOOLS_OPENED": "DEVTOOLS_OPENED",
  "KEYBOARD_SHORTCUT": "KEYBOARD_SHORTCUT",
  "COPY_ATTEMPT": "KEYBOARD_SHORTCUT",
  "WINDOW_BLUR": "WINDOW_BLUR",
  "IP_CHANGE": "IP_CHANGE",
  "VM_DETECTED": "VM_DETECTED",
  "SCREEN_SHARE_STOPPED": "SCREEN_SHARE_STOPPED",
  "SCREEN_RECORDING": "SCREEN_SHARE_STOPPED",
  "VPN_DISCONNECT": "VPN_DISCONNECT",
  "VPN_IP_MISMATCH": "VPN_IP_MISMATCH",
  "UNAUTHORIZED_APPLICATION": "UNAUTHORIZED_APPLICATION",
  "VIRTUAL_CAMERA_DETECTED": "VIRTUAL_CAMERA_DETECTED",
  "REMOTE_SESSION_DETECTED": "REMOTE_SESSION_DETECTED",
  "VIRTUAL_MACHINE_DETECTED": "VIRTUAL_MACHINE_DETECTED",
  "MULTIPLE_DISPLAYS": "MULTIPLE_DISPLAYS",
  "AGENT_DISCONNECTED": "AGENT_DISCONNECTED",
  "AGENT_TAMPERED": "AGENT_TAMPERED",
  "AGENT_POLICY_INVALID": "AGENT_POLICY_INVALID"
})

export const CANONICAL_SEVERITY = Object.freeze({
  "TAB_SWITCH": "MEDIUM",
  "FULLSCREEN_EXIT": "HIGH",
  "MULTIPLE_FACES": "HIGH",
  "NO_FACE": "MEDIUM",
  "FACE_MISMATCH": "CRITICAL",
  "AUDIO_DETECTED": "MEDIUM",
  "VOICE_DETECTED": "HIGH",
  "SUSPICIOUS_OBJECT": "HIGH",
  "DEVTOOLS_OPENED": "CRITICAL",
  "KEYBOARD_SHORTCUT": "MEDIUM",
  "WINDOW_BLUR": "LOW",
  "IP_CHANGE": "CRITICAL",
  "VM_DETECTED": "CRITICAL",
  "SCREEN_SHARE_STOPPED": "MEDIUM",
  "VPN_DISCONNECT": "CRITICAL",
  "VPN_IP_MISMATCH": "CRITICAL",
  "UNAUTHORIZED_APPLICATION": "HIGH",
  "VIRTUAL_CAMERA_DETECTED": "CRITICAL",
  "REMOTE_SESSION_DETECTED": "CRITICAL",
  "VIRTUAL_MACHINE_DETECTED": "HIGH",
  "MULTIPLE_DISPLAYS": "MEDIUM",
  "AGENT_DISCONNECTED": "HIGH",
  "AGENT_TAMPERED": "CRITICAL",
  "AGENT_POLICY_INVALID": "HIGH"
})

export const FLAG_COOLDOWNS = Object.freeze({
  "TAB_SWITCH": 2000,
  "FULLSCREEN_EXIT": 2000,
  "MULTIPLE_FACES": 3000,
  "NO_FACE": 3000,
  "FACE_MISMATCH": 5000,
  "AUDIO_DETECTED": 3000,
  "VOICE_DETECTED": 3000,
  "SUSPICIOUS_OBJECT": 5000,
  "DEVTOOLS_OPENED": 5000,
  "KEYBOARD_SHORTCUT": 1000,
  "WINDOW_BLUR": 2000,
  "IP_CHANGE": 10000,
  "VM_DETECTED": 10000,
  "SCREEN_SHARE_STOPPED": 5000,
  "VPN_DISCONNECT": 10000,
  "VPN_IP_MISMATCH": 10000,
  "UNAUTHORIZED_APPLICATION": 5000,
  "VIRTUAL_CAMERA_DETECTED": 5000,
  "REMOTE_SESSION_DETECTED": 5000,
  "VIRTUAL_MACHINE_DETECTED": 10000,
  "MULTIPLE_DISPLAYS": 5000,
  "AGENT_DISCONNECTED": 15000,
  "AGENT_TAMPERED": 5000,
  "AGENT_POLICY_INVALID": 15000,
  "DEFAULT": 3000
})

export function normalizeViolationType(clientType) {
  if (!clientType || typeof clientType !== 'string') return null
  const mapped = CLIENT_VIOLATION_MAP[clientType] || CLIENT_VIOLATION_MAP[clientType.toUpperCase()]
  return mapped || null
}

export function isValidViolationType(type) {
  return Boolean(type && VIOLATION_TYPES[type])
}
